a_tuple = (1, 2, 3, 2, 1, 1, 1)

print("All values:", a_tuple)
print("Value of first element:", a_tuple[0])
print("Value of third element:", a_tuple[2])
print("Number of 1s:", a_tuple.count(1))
print("Number of 2s:", a_tuple.count(2))
print("Number of 3s:", a_tuple.count(3))
print("Index of 1st 2:", a_tuple.index(2, 1))
print("Index of 2nd 2:", a_tuple.index(2, 3))
